set(_CATKIN_CURRENT_PACKAGE "topic_example")
set(topic_example_VERSION "0.0.0")
set(topic_example_MAINTAINER "kexue <kexue@todo.todo>")
set(topic_example_PACKAGE_FORMAT "2")
set(topic_example_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy")
set(topic_example_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "tf")
set(topic_example_BUILDTOOL_DEPENDS "catkin")
set(topic_example_BUILDTOOL_EXPORT_DEPENDS )
set(topic_example_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy")
set(topic_example_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "tf")
set(topic_example_TEST_DEPENDS )
set(topic_example_DOC_DEPENDS )
set(topic_example_URL_WEBSITE "")
set(topic_example_URL_BUGTRACKER "")
set(topic_example_URL_REPOSITORY "")
set(topic_example_DEPRECATED "")